export const productsBrands = [
  "Puma Unisex",
  "Puma",
  "Adidas",
  "Vector X Thunder",
  "Nivia Storm",
  "Nike Unisex",
  "Cosco",
  "Senstone",
  "CA Sports",
  "Sky Gold",
  "SMT MUFC",
  "Kookaburra",
  "Slazenger",
  "New Balance",
  "Spartan",
  "SG (Sanspareils Greenlands)",
  "Gray-Nicolls",
  "Gunn Moore",
  "Mikasa",
  "Molten",
  "Spalding",
  "Wilson",
  "Rawlings",
  "Penn",
  "Dudley",
  "Bauer",
  "CCM",
  "Speedo",
  "Arena",
  "Asics",
];
